"""Build notebooks/congressional_civility.ipynb (interactive data + plots + toxicity check)."""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []


def md(text: str) -> None:
    cells.append(nbf.v4.new_markdown_cell(text.strip("\n")))


def code(text: str) -> None:
    cells.append(nbf.v4.new_code_cell(text.strip("\n")))


md(r"""
# Congressional profanity, slurs, and formal courtesy — interactive explorer

Explore three word-pattern measures in the U.S. Congressional Record, **1873–present**, and
interact with the underlying data and plots.

**Data**
- 1873–2017: Stanford *hein* corpus (Gentzkow–Shapiro–Taddy), speaker-segmented with party.
- 2017–present: GovInfo CREC (whole-day package zips), segmented into speaker turns; party
  from MODS `congMember@party`.

**What we measure** (all rates are per 1,000 words, split by speaker party):
- *Formal courtesy* — parliamentary address and deference ("the gentleman from",
  "my distinguished colleague", "I yield").
- *Profanity* — a hand-curated list of genuine curse and obscene forms, split into mild and
  strong tiers, excluding neutral topical terms ("sex trafficking", "erected").
- *Slurs* — US ethnic, sexual-orientation and gender-identity, and disability slurs drawn
  from Wikipedia's slur lists and cross-checked against the Kaggle *Profanities in English*
  collection. Forms that are also ordinary words, names, or clinical terms ("chink in the
  armor", "Redskins", "queer", "retarded") are audit-only, and verb uses ("retard the growth")
  are excluded. See `analysis/score/lexicons/slurs_provenance.tsv`.

**Matching.** Formal courtesy uses morphological variants ("colleague"→"colleagues",
"gentleman"→"gentlemen"). Profanity and slurs use exact curated forms to avoid unsafe or
ambiguous expansions. A multi-word slur is counted once, not once per component word.

> These are descriptive counts. They miss sarcasm and target identity, and a member who
> repeats a slur to condemn it is still counted. OCR noise in pre-2011 scanned text is a known
> residual limitation.
""")

code(r"""
import sys, glob
import json
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

# Make the analysis package importable when running from notebooks/.
ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))

from analysis.plotting import theme, charts   # shared Substack-style toolkit
from analysis.score.registry import HEADLINE_METRICS
from analysis.viz import _by_congress_party, _by_year_chamber_party
theme.apply()

METRICS = ROOT / "data" / "processed" / "metrics" / "civility_metrics.parquet"
assert METRICS.exists(), f"Run `python -m analysis.run aggregate` first; missing {METRICS}"
m = pd.read_parquet(METRICS)
floor = m[m.chamber.isin(["house", "senate"])].copy()
print(f"metrics rows: {len(m)}  | congresses {m.congress.min()}–{m.congress.max()}"
      f" (years {m.year.min()}–{m.year.max()})")
m.head()
""")

md(r"""
## Provenance and coverage

These artifacts are generated by the production pipeline. Source overlap and validation tables
appear only after those stages have actually run.
""")

code(r"""
SOURCE_META = ROOT / "data" / "processed" / "coverage" / "source_metadata.json"
COVERAGE = ROOT / "data" / "processed" / "coverage" / "turn_coverage.parquet"
if SOURCE_META.exists():
    print(json.dumps(json.loads(SOURCE_META.read_text()), indent=2))
if COVERAGE.exists():
    coverage = pd.read_parquet(COVERAGE)
    display(coverage.tail(12)) if "display" in globals() else print(coverage.tail(12).to_string())

CALIBRATION = ROOT / "data" / "processed" / "calibration" / "calibration_summary.csv"
if CALIBRATION.exists():
    calibration = pd.read_csv(CALIBRATION)
    display(calibration) if "display" in globals() else print(calibration.to_string(index=False))
else:
    print("Overlap calibration has not been generated yet.")

VALIDATION_REPORT = ROOT / "data" / "processed" / "validation" / "precision_recall.csv"
if VALIDATION_REPORT.exists():
    validation = pd.read_csv(VALIDATION_REPORT)
    display(validation) if "display" in globals() else print(validation.to_string(index=False))
else:
    print("Model-assisted validation has not been completed yet.")
""")

md(r"""
## 1. Re-aggregate to (Congress, party)

The metrics table is stored at `(congress, chamber, party)` granularity with **raw hit
counts + word totals**, so we can re-aggregate to any grouping while keeping rates
word-weighted (never averaging rates-of-rates).
""")

code(r"""
# Reuse the production aggregation/rate definitions instead of duplicating formulas here.
g = _by_congress_party(floor)
g[g.party.isin(["D","R"])].tail(6)
""")

md(r"""
## 2. By party **and** chamber (House vs Senate)

The same metrics split four ways — party (colour) × chamber (House solid, Senate dashed).
Aggregated from raw hits/words at `(congress, chamber, party)` so rates stay word-weighted.
""")

code(r"""
CHAM_STYLE = {"house": "-", "senate": "--"}
CHAM_LABEL = {"house": "House", "senate": "Senate"}

gc = _by_year_chamber_party(floor)

def plot_by_chamber(metric, title, ylabel="hits per 1,000 words"):
    fig, ax = charts.new_figure(figsize=(11, 6))
    for p in ("D","R"):
        for ch in ("house","senate"):
            sub = gc[(gc.party==p) & (gc.chamber==ch)].sort_values("year")
            if sub.empty: continue
            charts.line(ax, sub["year"], sub[metric], color=theme.PARTY_COLORS[p],
                        label=f"{theme.PARTY_LABELS[p]} — {CHAM_LABEL[ch]}",
                        linestyle=CHAM_STYLE[ch], linewidth=2.0, markersize=3)
    charts.style_axes(ax, f"{title} — by party & chamber", "Year", ylabel,
                      subtitle="solid = House, dashed = Senate")
    ax.legend(loc="best", frameon=False, labelcolor=theme.TEXT, fontsize=9)
    plt.show()

for spec in HEADLINE_METRICS:
    plot_by_chamber(spec.rate, spec.title)
""")

md(r"""
## 3. Plot any metric by party (overall)

Change `METRIC` to any `*_per_1k` column and re-run.
""")

code(r"""
def plot_metric(metric, title, ylabel="hits per 1,000 words", parties=("D","R")):
    fig, ax = charts.new_figure(figsize=(10, 5.5))
    for p in parties:
        sub = g[g.party == p].sort_values("year")
        charts.line(ax, sub["year"], sub[metric], color=theme.PARTY_COLORS[p],
                    label=theme.PARTY_LABELS[p])
    charts.style_axes(ax, title, "Year", ylabel)
    ax.legend(loc="best", frameon=False, labelcolor=theme.TEXT)
    plt.show()
    return fig

METRIC = "profanity_strong_per_1k"
plot_metric(METRIC, "Strong profanity");
""")

code(r"""
# Headline panels come from the same registry used by aggregation and production plots.
for spec in HEADLINE_METRICS:
    plot_metric(spec.rate, spec.title);
""")

md(r"""
## 4. Score a sample of turns

Score real source turns with the production scorer and inspect which spans matched. Reading
the matches is the quickest way to judge whether a count reflects the speaker's own language.
""")

code(r"""
from analysis.score.scorers import Scorers

TURN_FILES = sorted(glob.glob(str(ROOT / "data" / "interim" / "turns" / "*.parquet")))
assert TURN_FILES, "No turn parquet files; run the ingest step first."

# Sample recent turns (bulk GovInfo if present, else the newest available file).
recent = [f for f in TURN_FILES if "govinfo_bulk_" in f] or TURN_FILES[-1:]
sample = (pd.read_parquet(recent[-1], columns=["party","text","is_procedural"])
            .query("~is_procedural and text.str.len() > 0", engine="python")
            .sample(2000, random_state=0))

scorer = Scorers()
scored = sample.assign(**pd.DataFrame(
    [scorer.score_turn(t) for t in sample.text], index=sample.index))
for key, rate in (("formal_courtesy_hits", "formal_courtesy_per_1k"),
                  ("profanity_hits", "profanity_per_1k"),
                  ("slur_hits", "slurs_per_1k")):
    scored[rate] = 1000 * scored[key] / scored.n_words.clip(lower=1)
scored.groupby("party")[["formal_courtesy_per_1k","profanity_per_1k","slurs_per_1k"]].mean()
""")

code(r"""
# Show the matched spans in a few turns that contain profanity or a slur.
flagged = scored[(scored.profanity_hits > 0) | (scored.slur_hits > 0)].head(5)
for text in flagged.text:
    for signal, spans in scorer.signal_spans(text).items():
        for start, end in spans:
            print(f"{signal:16s} ...{text[max(0, start-60):end+60]}...")
    print()
""")

md(r"""
## 5. Caveats

- **Lexicons are literal.** They miss sarcasm and many forms of negation. Quoted material is
  excluded from member-level rates, but a member who repeats a slur to describe or condemn it
  is still counted.
- **Party = speaker's party**, not the target's.
- **Source discontinuity at 2017** (hein → GovInfo) — the dotted line on every chart. Treat
  cross-boundary jumps cautiously; compare within-source trends.
- **Segmentation error** on the GovInfo side (regex speaker splitting) is measured but non-zero.
- **Validation must be re-run for codebook v5.** Earlier precision/recall figures were measured
  on the previous codebook.
""")

def main() -> None:
    nb["cells"] = cells
    out = Path("notebooks/congressional_civility.ipynb")
    out.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, str(out))
    print(f"wrote {out} ({len(cells)} cells)")


if __name__ == "__main__":
    main()
