"""Build notebooks/congressional_civility.ipynb (interactive data + plots + toxicity check)."""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []


def md(text: str) -> None:
    cells.append(nbf.v4.new_markdown_cell(text.strip("\n")))


def code(text: str) -> None:
    cells.append(nbf.v4.new_code_cell(text.strip("\n")))


md(r"""
# Congressional civility & "toxicity" — interactive explorer

Explore changes in comity and conflict language in the U.S. Congressional Record,
**1873–2026**, and interact with the underlying data and plots.

**Data**
- 1873–2017: Stanford *hein* corpus (Gentzkow–Shapiro–Taddy), speaker-segmented with party.
- 2017–present: GovInfo CREC (whole-day package zips), segmented into speaker turns; party
  from MODS `congMember@party`.

**What we measure** (all rates are per 1,000 words, split by speaker party):
- *Formulaic courtesy* — parliamentary address/deference ("the gentleman from").
- *Gratitude / praise* — thanks, commendation, appreciation, or explicit respect.
- *Bipartisan cooperation* — explicit cross-aisle work and bipartisan spirit.
- *Personal disrespect / attack* — a high-precision insult and attack lexicon.
- *Misconduct allegations* — corruption, fraud, perjury, obstruction, and similar allegation
  language; this is **not evidence that misconduct occurred**.
- *Profanity* — a narrow, hand-curated list of genuine curse/obscene forms, excluding neutral
  topical terms.
- *Identity slurs* — a separate exact-match diagnostic requiring quotation/context review.
- *Ideological labels* — tracked separately, not automatically treated as disrespect.
- *Cross-party reference context* — out-party references plus comity, disrespect, or misconduct
  terms nearby, reported both per 1,000 words and per 100 reference contexts. Proximity does not
  prove that the phrase targets the party.
- *Sentiment / "toxicity"* — VADER sentence-level compound + negative-affect share (see the
  toxicity section below for exactly what this means and how we validate it).

**Keyword matching is usually fuzzy.** Most lexicon terms are matched with morphological variants
(plurals and verb forms: "colleague"→"colleagues", "coward"→"cowards"; irregular plurals like
"gentleman"→"gentlemen"), so recall doesn't hinge on listing every inflection. (OCR noise in the
pre-2011 scanned text is a known residual limitation — see caveats.) Profanity, identity slurs,
and misconduct allegations use exact curated forms to avoid unsafe or ambiguous expansions.

> **On the word "toxicity."** There is no single ground-truth "toxicity" label for a
> 150-year speech corpus. Here *toxicity* is only a shorthand for several disclosed lexical
> signals; it is not a ground-truth label. The measures are transparent and reproducible, but
> they miss sarcasm, quotation, some negation, and target identity. Optional checks below are
> diagnostics, not independent human validation.
""")

code(r"""
import sys, glob
import json
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

# Make the analysis package importable when running from notebooks/.
ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))

from analysis.plotting import theme, charts   # shared Substack-style toolkit
from analysis.score.registry import HEADLINE_METRICS
from analysis.viz import _by_congress_party, _by_year_chamber_party
theme.apply()

METRICS = ROOT / "data" / "processed" / "metrics" / "civility_metrics.parquet"
assert METRICS.exists(), f"Run `python -m analysis.run aggregate` first; missing {METRICS}"
m = pd.read_parquet(METRICS)
floor = m[m.chamber.isin(["house", "senate"])].copy()
print(f"metrics rows: {len(m)}  | congresses {m.congress.min()}–{m.congress.max()}"
      f" (years {m.year.min()}–{m.year.max()})")
m.head()
""")

md(r"""
## Provenance and coverage

These artifacts are generated by the production pipeline. Source overlap and validation tables
appear only after those stages have actually run.
""")

code(r"""
SOURCE_META = ROOT / "data" / "processed" / "coverage" / "source_metadata.json"
COVERAGE = ROOT / "data" / "processed" / "coverage" / "turn_coverage.parquet"
if SOURCE_META.exists():
    print(json.dumps(json.loads(SOURCE_META.read_text()), indent=2))
if COVERAGE.exists():
    coverage = pd.read_parquet(COVERAGE)
    display(coverage.tail(12)) if "display" in globals() else print(coverage.tail(12).to_string())

CALIBRATION = ROOT / "data" / "processed" / "calibration" / "calibration_summary.csv"
if CALIBRATION.exists():
    calibration = pd.read_csv(CALIBRATION)
    display(calibration) if "display" in globals() else print(calibration.to_string(index=False))
else:
    print("Overlap calibration has not been generated yet.")

VALIDATION_REPORT = ROOT / "data" / "processed" / "validation" / "precision_recall.csv"
if VALIDATION_REPORT.exists():
    validation = pd.read_csv(VALIDATION_REPORT)
    display(validation) if "display" in globals() else print(validation.to_string(index=False))
else:
    print("Model-assisted validation has not been completed yet.")
""")

md(r"""
## 1. Re-aggregate to (Congress, party)

The metrics table is stored at `(congress, chamber, party)` granularity with **raw hit
counts + word totals**, so we can re-aggregate to any grouping while keeping rates
word-weighted (never averaging rates-of-rates).
""")

code(r"""
# Reuse the production aggregation/rate definitions instead of duplicating formulas here.
g = _by_congress_party(floor)
g[g.party.isin(["D","R"])].tail(6)
""")

md(r"""
## 2. By party **and** chamber (House vs Senate)

The same metrics split four ways — party (colour) × chamber (House solid, Senate dashed).
Aggregated from raw hits/words at `(congress, chamber, party)` so rates stay word-weighted.
""")

code(r"""
CHAM_STYLE = {"house": "-", "senate": "--"}
CHAM_LABEL = {"house": "House", "senate": "Senate"}

gc = _by_year_chamber_party(floor)

def plot_by_chamber(metric, title, ylabel="hits per 1,000 words"):
    fig, ax = charts.new_figure(figsize=(11, 6))
    for p in ("D","R"):
        for ch in ("house","senate"):
            sub = gc[(gc.party==p) & (gc.chamber==ch)].sort_values("year")
            if sub.empty: continue
            charts.line(ax, sub["year"], sub[metric], color=theme.PARTY_COLORS[p],
                        label=f"{theme.PARTY_LABELS[p]} — {CHAM_LABEL[ch]}",
                        linestyle=CHAM_STYLE[ch], linewidth=2.0, markersize=3)
    charts.style_axes(ax, f"{title} — by party & chamber", "Year", ylabel,
                      subtitle="solid = House, dashed = Senate")
    ax.legend(loc="best", frameon=False, labelcolor=theme.TEXT, fontsize=9)
    plt.show()

plot_by_chamber("formal_courtesy_per_1k", "Formulaic courtesy / deference")
plot_by_chamber("cooperation_per_1k", "Bipartisan cooperation language")
plot_by_chamber("hostility_per_1k", "Personal disrespect / attack language")
plot_by_chamber("misconduct_per_1k", "Misconduct allegation language")
""")

md(r"""
## 3. Plot any metric by party (overall)

Change `METRIC` to any `*_per_1k` column and re-run.
""")

code(r"""
def plot_metric(metric, title, ylabel="hits per 1,000 words", parties=("D","R")):
    fig, ax = charts.new_figure(figsize=(10, 5.5))
    for p in parties:
        sub = g[g.party == p].sort_values("year")
        charts.line(ax, sub["year"], sub[metric], color=theme.PARTY_COLORS[p],
                    label=theme.PARTY_LABELS[p])
    charts.style_axes(ax, title, "Year", ylabel)
    ax.legend(loc="best", frameon=False, labelcolor=theme.TEXT)
    plt.show()
    return fig

METRIC = "comity_per_1k"
plot_metric(METRIC, "Comity / deference phrases");
""")

code(r"""
# Headline panels come from the same registry used by aggregation and production plots.
for spec in HEADLINE_METRICS:
    plot_metric(spec.rate, spec.title);
""")

code(r"""
# Context-normalized cross-party diagnostics: share of out-party references whose
# sentence/clause context (bounded at ±300 characters for OCR run-ons) contains each
# language category. Separate nearby-intensity metrics use ±200-character windows.
for metric, title in [
    ("outgroup_comity_contexts_per_100_refs", "Out-party references with nearby comity"),
    ("outgroup_hostility_contexts_per_100_refs", "Out-party references with nearby disrespect"),
    ("outgroup_misconduct_contexts_per_100_refs", "Out-party references with nearby misconduct allegations"),
]:
    plot_metric(metric, title, ylabel="contexts per 100 references");
""")

md(r"""
## 4. Toxicity — are we doing it right?

"Toxicity" here is shorthand for disclosed signals: personal disrespect + profanity rates and
**VADER** negative sentiment. Two methodological points we get right:

1. **Sentence-level VADER.** VADER's `compound` score saturates on long text, so scoring a whole
   speech (or a fixed truncation of it) is biased. `Scorers._sentiment` splits each turn into
   sentences, scores each, and averages — the granularity VADER is designed for — and reports the
   mean **negative-affect share**.
2. **Word-weighted rates.** Lexicon counts are normalised per 1,000 words, never compared as raw
   counts across eras of differing verbosity.

Below we score a real sample of source turns and inspect whether lexical signals and VADER agree.
Correlation is a diagnostic, not proof that either measure is ground truth.
""")

code(r"""
from analysis.score.scorers import Scorers

TURN_FILES = sorted(glob.glob(str(ROOT / "data" / "interim" / "turns" / "*.parquet")))
assert TURN_FILES, "No turn parquet files; run the ingest step first."

# Sample recent turns (bulk GovInfo if present, else the newest available file).
recent = [f for f in TURN_FILES if "govinfo_bulk_" in f] or TURN_FILES[-1:]
sample = (pd.read_parquet(recent[-1], columns=["party","text","is_procedural"])
            .query("~is_procedural and text.str.len() > 0", engine="python")
            .sample(2000, random_state=0))

scorer = Scorers(use_sentiment=True)   # VADER on (this smaller sample only)
scored = sample.assign(**pd.DataFrame(
    [scorer.score_turn(t, p) for t, p in zip(sample.text, sample.party)],
    index=sample.index)[["n_words","hostility_hits","profanity_hits","sentiment","neg_share"]])
scored["hostility_per_1k"] = 1000*scored.hostility_hits/scored.n_words.clip(lower=1)
scored["profanity_per_1k"] = 1000*scored.profanity_hits/scored.n_words.clip(lower=1)
scored[["party","n_words","hostility_per_1k","profanity_per_1k","sentiment","neg_share"]].describe()
""")

code(r"""
# Do the independent negativity signals agree? (lexical hostility/profanity vs VADER)
corr = scored[["hostility_per_1k","profanity_per_1k","neg_share","sentiment"]].corr(method="spearman")
print("Spearman correlations among negativity signals:")
try:
    display(corr.round(2))          # rich table in Jupyter
except NameError:
    print(corr.round(2))            # plain output elsewhere
print("\nInterpret correlations descriptively. Weak agreement means the signals capture different "
      "facets; even strong agreement would not establish accuracy.")
""")

md(r"""
## 5. Optional: validate against a real toxicity model (Detoxify)

The cell below is **optional and heavy** (installs `torch` + `transformers` and downloads a
model). It runs the Detoxify `original` classifier on a small sample and correlates its
`toxicity` probability with our lexical proxy. A positive correlation is evidence the fast
lexical measure tracks a modern toxicity model. That is a robustness diagnostic, not validation
against independent human ground truth.

Uncomment and run only if you want the validation (it does not affect the pipeline).
""")

code(r"""
# --- OPTIONAL: real transformer toxicity validation (slow; needs internet + torch) ---
# import subprocess, sys
# subprocess.run([sys.executable, "-m", "pip", "install", "-q", "detoxify"], check=True)
# from detoxify import Detoxify
# val = scored.sample(200, random_state=1).copy()
# tox = Detoxify("original").predict(list(val.text.str.slice(0, 2000)))["toxicity"]
# val["detoxify_toxicity"] = tox
# print("Spearman(lexical hostility/1k, Detoxify toxicity):",
#       round(val["hostility_per_1k"].corr(val["detoxify_toxicity"], method="spearman"), 3))
# print("Spearman(VADER neg_share,     Detoxify toxicity):",
#       round(val["neg_share"].corr(val["detoxify_toxicity"], method="spearman"), 3))
print("Optional Detoxify validation cell — uncomment the lines above to run it.")
""")

md(r"""
## 6. Caveats

- **Lexicons are literal.** They miss sarcasm, many forms of negation, and **quotation** — a
  member reading an opponent's words is scored as if they were their own. Profanity/attacks on
  the floor also often appear inside quoted material.
- **VADER is lexical**, tuned for modern English; 19th-century phrasing is out-of-distribution.
- **Source discontinuity at 2017** (hein → GovInfo) — the dotted line on every chart. Treat
  cross-boundary jumps cautiously; compare within-source trends.
- **Segmentation error** on the GovInfo side (regex speaker splitting) is measured but non-zero.
- **Party = speaker's party**, not the target's; "directed" measures use a text window around
  out-group references. They are labelled "near out-party references" because proximity alone
  does not prove who is being addressed.
- **Model-assisted validation is not human ground truth.** Completed rubric grading uses only real,
  blinded source passages, two independent model passes, disagreement adjudication, confidence,
  rationale, and preserved `turn_id` provenance.
""")

def main() -> None:
    nb["cells"] = cells
    out = Path("notebooks/congressional_civility.ipynb")
    out.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, str(out))
    print(f"wrote {out} ({len(cells)} cells)")


if __name__ == "__main__":
    main()
